# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files (x86)\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files (x86)\CMake\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "C:\Users\wathe\Google Drive\workspace\game_design"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "C:\Users\wathe\Google Drive\workspace\game_design"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files (x86)\CMake\bin\cmake-gui.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files (x86)\CMake\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\wathe\Google Drive\workspace\game_design\CMakeFiles" "C:\Users\wathe\Google Drive\workspace\game_design\CMakeFiles\progress.marks"
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\wathe\Google Drive\workspace\game_design\CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named LavaLeaper

# Build rule for target.
LavaLeaper: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 LavaLeaper
.PHONY : LavaLeaper

# fast build rule for target.
LavaLeaper/fast:
	$(MAKE) -f CMakeFiles\LavaLeaper.dir\build.make CMakeFiles/LavaLeaper.dir/build
.PHONY : LavaLeaper/fast

bin/LavaLeaper.obj: bin/LavaLeaper.cpp.obj

.PHONY : bin/LavaLeaper.obj

# target to build an object file
bin/LavaLeaper.cpp.obj:
	$(MAKE) -f CMakeFiles\LavaLeaper.dir\build.make CMakeFiles/LavaLeaper.dir/bin/LavaLeaper.cpp.obj
.PHONY : bin/LavaLeaper.cpp.obj

bin/LavaLeaper.i: bin/LavaLeaper.cpp.i

.PHONY : bin/LavaLeaper.i

# target to preprocess a source file
bin/LavaLeaper.cpp.i:
	$(MAKE) -f CMakeFiles\LavaLeaper.dir\build.make CMakeFiles/LavaLeaper.dir/bin/LavaLeaper.cpp.i
.PHONY : bin/LavaLeaper.cpp.i

bin/LavaLeaper.s: bin/LavaLeaper.cpp.s

.PHONY : bin/LavaLeaper.s

# target to generate assembly for a file
bin/LavaLeaper.cpp.s:
	$(MAKE) -f CMakeFiles\LavaLeaper.dir\build.make CMakeFiles/LavaLeaper.dir/bin/LavaLeaper.cpp.s
.PHONY : bin/LavaLeaper.cpp.s

src/GameLogic.obj: src/GameLogic.cpp.obj

.PHONY : src/GameLogic.obj

# target to build an object file
src/GameLogic.cpp.obj:
	$(MAKE) -f CMakeFiles\LavaLeaper.dir\build.make CMakeFiles/LavaLeaper.dir/src/GameLogic.cpp.obj
.PHONY : src/GameLogic.cpp.obj

src/GameLogic.i: src/GameLogic.cpp.i

.PHONY : src/GameLogic.i

# target to preprocess a source file
src/GameLogic.cpp.i:
	$(MAKE) -f CMakeFiles\LavaLeaper.dir\build.make CMakeFiles/LavaLeaper.dir/src/GameLogic.cpp.i
.PHONY : src/GameLogic.cpp.i

src/GameLogic.s: src/GameLogic.cpp.s

.PHONY : src/GameLogic.s

# target to generate assembly for a file
src/GameLogic.cpp.s:
	$(MAKE) -f CMakeFiles\LavaLeaper.dir\build.make CMakeFiles/LavaLeaper.dir/src/GameLogic.cpp.s
.PHONY : src/GameLogic.cpp.s

src/GameView.obj: src/GameView.cpp.obj

.PHONY : src/GameView.obj

# target to build an object file
src/GameView.cpp.obj:
	$(MAKE) -f CMakeFiles\LavaLeaper.dir\build.make CMakeFiles/LavaLeaper.dir/src/GameView.cpp.obj
.PHONY : src/GameView.cpp.obj

src/GameView.i: src/GameView.cpp.i

.PHONY : src/GameView.i

# target to preprocess a source file
src/GameView.cpp.i:
	$(MAKE) -f CMakeFiles\LavaLeaper.dir\build.make CMakeFiles/LavaLeaper.dir/src/GameView.cpp.i
.PHONY : src/GameView.cpp.i

src/GameView.s: src/GameView.cpp.s

.PHONY : src/GameView.s

# target to generate assembly for a file
src/GameView.cpp.s:
	$(MAKE) -f CMakeFiles\LavaLeaper.dir\build.make CMakeFiles/LavaLeaper.dir/src/GameView.cpp.s
.PHONY : src/GameView.cpp.s

src/Platform.obj: src/Platform.cpp.obj

.PHONY : src/Platform.obj

# target to build an object file
src/Platform.cpp.obj:
	$(MAKE) -f CMakeFiles\LavaLeaper.dir\build.make CMakeFiles/LavaLeaper.dir/src/Platform.cpp.obj
.PHONY : src/Platform.cpp.obj

src/Platform.i: src/Platform.cpp.i

.PHONY : src/Platform.i

# target to preprocess a source file
src/Platform.cpp.i:
	$(MAKE) -f CMakeFiles\LavaLeaper.dir\build.make CMakeFiles/LavaLeaper.dir/src/Platform.cpp.i
.PHONY : src/Platform.cpp.i

src/Platform.s: src/Platform.cpp.s

.PHONY : src/Platform.s

# target to generate assembly for a file
src/Platform.cpp.s:
	$(MAKE) -f CMakeFiles\LavaLeaper.dir\build.make CMakeFiles/LavaLeaper.dir/src/Platform.cpp.s
.PHONY : src/Platform.cpp.s

src/Player.obj: src/Player.cpp.obj

.PHONY : src/Player.obj

# target to build an object file
src/Player.cpp.obj:
	$(MAKE) -f CMakeFiles\LavaLeaper.dir\build.make CMakeFiles/LavaLeaper.dir/src/Player.cpp.obj
.PHONY : src/Player.cpp.obj

src/Player.i: src/Player.cpp.i

.PHONY : src/Player.i

# target to preprocess a source file
src/Player.cpp.i:
	$(MAKE) -f CMakeFiles\LavaLeaper.dir\build.make CMakeFiles/LavaLeaper.dir/src/Player.cpp.i
.PHONY : src/Player.cpp.i

src/Player.s: src/Player.cpp.s

.PHONY : src/Player.s

# target to generate assembly for a file
src/Player.cpp.s:
	$(MAKE) -f CMakeFiles\LavaLeaper.dir\build.make CMakeFiles/LavaLeaper.dir/src/Player.cpp.s
.PHONY : src/Player.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... LavaLeaper
	@echo ... bin/LavaLeaper.obj
	@echo ... bin/LavaLeaper.i
	@echo ... bin/LavaLeaper.s
	@echo ... src/GameLogic.obj
	@echo ... src/GameLogic.i
	@echo ... src/GameLogic.s
	@echo ... src/GameView.obj
	@echo ... src/GameView.i
	@echo ... src/GameView.s
	@echo ... src/Platform.obj
	@echo ... src/Platform.i
	@echo ... src/Platform.s
	@echo ... src/Player.obj
	@echo ... src/Player.i
	@echo ... src/Player.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

