# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/alex/Desktop/game_design

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/alex/Desktop/game_design

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/alex/Desktop/game_design/CMakeFiles /Users/alex/Desktop/game_design/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/alex/Desktop/game_design/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named LavaLeaper

# Build rule for target.
LavaLeaper: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LavaLeaper
.PHONY : LavaLeaper

# fast build rule for target.
LavaLeaper/fast:
	$(MAKE) -f CMakeFiles/LavaLeaper.dir/build.make CMakeFiles/LavaLeaper.dir/build
.PHONY : LavaLeaper/fast

bin/LavaLeaper.o: bin/LavaLeaper.cpp.o

.PHONY : bin/LavaLeaper.o

# target to build an object file
bin/LavaLeaper.cpp.o:
	$(MAKE) -f CMakeFiles/LavaLeaper.dir/build.make CMakeFiles/LavaLeaper.dir/bin/LavaLeaper.cpp.o
.PHONY : bin/LavaLeaper.cpp.o

bin/LavaLeaper.i: bin/LavaLeaper.cpp.i

.PHONY : bin/LavaLeaper.i

# target to preprocess a source file
bin/LavaLeaper.cpp.i:
	$(MAKE) -f CMakeFiles/LavaLeaper.dir/build.make CMakeFiles/LavaLeaper.dir/bin/LavaLeaper.cpp.i
.PHONY : bin/LavaLeaper.cpp.i

bin/LavaLeaper.s: bin/LavaLeaper.cpp.s

.PHONY : bin/LavaLeaper.s

# target to generate assembly for a file
bin/LavaLeaper.cpp.s:
	$(MAKE) -f CMakeFiles/LavaLeaper.dir/build.make CMakeFiles/LavaLeaper.dir/bin/LavaLeaper.cpp.s
.PHONY : bin/LavaLeaper.cpp.s

src/GameLogic.o: src/GameLogic.cpp.o

.PHONY : src/GameLogic.o

# target to build an object file
src/GameLogic.cpp.o:
	$(MAKE) -f CMakeFiles/LavaLeaper.dir/build.make CMakeFiles/LavaLeaper.dir/src/GameLogic.cpp.o
.PHONY : src/GameLogic.cpp.o

src/GameLogic.i: src/GameLogic.cpp.i

.PHONY : src/GameLogic.i

# target to preprocess a source file
src/GameLogic.cpp.i:
	$(MAKE) -f CMakeFiles/LavaLeaper.dir/build.make CMakeFiles/LavaLeaper.dir/src/GameLogic.cpp.i
.PHONY : src/GameLogic.cpp.i

src/GameLogic.s: src/GameLogic.cpp.s

.PHONY : src/GameLogic.s

# target to generate assembly for a file
src/GameLogic.cpp.s:
	$(MAKE) -f CMakeFiles/LavaLeaper.dir/build.make CMakeFiles/LavaLeaper.dir/src/GameLogic.cpp.s
.PHONY : src/GameLogic.cpp.s

src/GameView.o: src/GameView.cpp.o

.PHONY : src/GameView.o

# target to build an object file
src/GameView.cpp.o:
	$(MAKE) -f CMakeFiles/LavaLeaper.dir/build.make CMakeFiles/LavaLeaper.dir/src/GameView.cpp.o
.PHONY : src/GameView.cpp.o

src/GameView.i: src/GameView.cpp.i

.PHONY : src/GameView.i

# target to preprocess a source file
src/GameView.cpp.i:
	$(MAKE) -f CMakeFiles/LavaLeaper.dir/build.make CMakeFiles/LavaLeaper.dir/src/GameView.cpp.i
.PHONY : src/GameView.cpp.i

src/GameView.s: src/GameView.cpp.s

.PHONY : src/GameView.s

# target to generate assembly for a file
src/GameView.cpp.s:
	$(MAKE) -f CMakeFiles/LavaLeaper.dir/build.make CMakeFiles/LavaLeaper.dir/src/GameView.cpp.s
.PHONY : src/GameView.cpp.s

src/Player.o: src/Player.cpp.o

.PHONY : src/Player.o

# target to build an object file
src/Player.cpp.o:
	$(MAKE) -f CMakeFiles/LavaLeaper.dir/build.make CMakeFiles/LavaLeaper.dir/src/Player.cpp.o
.PHONY : src/Player.cpp.o

src/Player.i: src/Player.cpp.i

.PHONY : src/Player.i

# target to preprocess a source file
src/Player.cpp.i:
	$(MAKE) -f CMakeFiles/LavaLeaper.dir/build.make CMakeFiles/LavaLeaper.dir/src/Player.cpp.i
.PHONY : src/Player.cpp.i

src/Player.s: src/Player.cpp.s

.PHONY : src/Player.s

# target to generate assembly for a file
src/Player.cpp.s:
	$(MAKE) -f CMakeFiles/LavaLeaper.dir/build.make CMakeFiles/LavaLeaper.dir/src/Player.cpp.s
.PHONY : src/Player.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... LavaLeaper"
	@echo "... bin/LavaLeaper.o"
	@echo "... bin/LavaLeaper.i"
	@echo "... bin/LavaLeaper.s"
	@echo "... src/GameLogic.o"
	@echo "... src/GameLogic.i"
	@echo "... src/GameLogic.s"
	@echo "... src/GameView.o"
	@echo "... src/GameView.i"
	@echo "... src/GameView.s"
	@echo "... src/Player.o"
	@echo "... src/Player.i"
	@echo "... src/Player.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

